services:

  app:
    image: home-rental-service:v1.0.1
    container_name: home-rental-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/home_rental_db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: changeme
      JWT_SECRET: xbBPqZAxi5mEfhkrQGm1z2MvNOQcYkkaisktXr15CAk=
    depends_on:
      db:
        condition: service_healthy
    networks:
      - home-rental-net
    restart: on-failure

  db:
    image: postgres:16-alpine
    container_name: home-rental-db
    environment:
      POSTGRES_DB: home_rental_db
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: changeme
    volumes:
      - home-rental-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d home_rental_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - home-rental-net
    restart: unless-stopped

volumes:
  home-rental-db-data:

networks:
  home-rental-net:
    driver: bridge
